# ==========================================
# CONFIGURACIÓN GLOBAL - RED HUMANA (RT STYLE)
# ==========================================
title: "Adestrat | Carlos"
description: "Opinión"
/* CAMBIO: Se asegura la URL base completa para Open Graph */
url: "https://adestrat.com"
baseurl: ""
enforce_ssl: true

# IDENTIDAD DEL AUTOR (Bloque necesario para la foto en los posts)
author:
  name: Carlos Hernández
  avatar: "/perfil.png"
  twitter_username: cafrhein

# IMPORTANTE: Diseño propio
theme: null

# CONFIGURACIÓN DE MOTOR
markdown: kramdown
highlighter: rouge
lsi: false

# ESTRUCTURA DE ARCHIVOS
include: [_posts, _layouts, assets]
exclude: [Gemfile, Gemfile.lock, node_modules, vendor, .github]

# CONFIGURACIÓN DE PERMALINKS
permalink: /:categories/:title/

# VALORES POR DEFECTO
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "Actualidad"
  - scope:
      path: ""
    values:
      layout: "default"
