title: "Adestrat | Red Humana"
description: "Estrategia e Ingeniería de la Reciprocidad"
remote_theme: pages-themes/minimal

# CONFIGURACIÓN DE RUTAS
baseurl: "/muro"
url: "https://cafrhein.github.io"

# Configuración de Jekyll
markdown: kramdown
highlighter: rouge
lsi: false

# Forzar la lectura de carpetas
include: [_posts, _layouts]
exclude: [Gemfile, Gemfile.lock, node_modules, vendor]

# Configuración de Posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
